CREATE DATABASE Enterprise
GO

USE Enterprise

CREATE TABLE POSITIONS(
Position 	VARCHAR (12) NOT NULL PRIMARY KEY
)

CREATE TABLE EMPLOYEE(
EmployeeID  INT NOT NULL PRIMARY KEY,
Position    VARCHAR(12),
Nationality VARCHAR(45),
FirstName   VARCHAR(45),
LastName 	VARCHAR(45),
Email		VARCHAR(45),

FOREIGN KEY(Position)
REFERENCES POSITIONS(Position)
ON DELETE CASCADE
ON UPDATE CASCADE
)

CREATE TABLE SUPERVISOR(
SupervisorID INT NOT NULL PRIMARY KEY,
FirstName    VARCHAR (45),
LastName     VARCHAR (45),
)

CREATE TABLE DEPARMENT(
DepartmentID   INT NOT NULL PRIMARY KEY,
SupervisorID   INT NOT NULL,
DepartmentName VARCHAR(45),
Location	   VARCHAR(45),

CONSTRAINT FK_SupervisorID
FOREIGN KEY(SupervisorID)
REFERENCES SUPERVISOR(SupervisorID)
ON DELETE CASCADE
ON UPDATE CASCADE
)

CREATE TABLE PAYROLL (
SupervisorID INT NOT NULL PRIMARY KEY,
EmployeeID   INT NOT NULL,
PayRate      INT NOT NULL,
HoursWorked  INT NOT NULL, 

CONSTRAINT FK_PAYROLL_EmployeeID
FOREIGN KEY (EmployeeID)
REFERENCES EMPLOYEE(EmployeeID)
ON DELETE NO ACTION 
ON UPDATE CASCADE,
)