CREATE DATABASE Futbol
GO

USE Futbol

CREATE TABLE POSITIONS(
Position	VARCHAR (12) NOT NULL PRIMARY KEY
)	

CREATE TABLE PLAYERS(
PlayerID	INT	NOT NULL PRIMARY KEY,
Position	VARCHAR(12) NOT NULL,
Nationality VARCHAR(45)	NULL,
FirstName	VARCHAR(45)	NULL,
LastName	VARCHAR(45)	NULL,

FOREIGN KEY (Position)
REFERENCES POSITIONS (Position)
ON DELETE CASCADE
ON UPDATE CASCADE 
)

CREATE TABLE COACHES(
CoachID		INT	NOT NULL PRIMARY KEY,
FirstName	VARCHAR(45) NULL,
LastName	VARCHAR(45) NULL,
)

CREATE TABLE TEAMS(
TeamID		INT	NOT NULL PRIMARY KEY,
CoachID		INT	NOT NULL,
TeamName	VARCHAR	(45)	NULL,
LeagueName	VARCHAR (45)	NULL,

CONSTRAINT FK_CoachID
FOREIGN KEY (CoachID)
REFERENCES COACHES(CoachID)
ON DELETE CASCADE
ON UPDATE CASCADE
)

CREATE TABLE ROSTER(
PlayerID	INT NOT NULL,
TeamID		INT NOT NULL,
PRIMARY KEY (PlayerID,TeamID),

CONSTRAINT FK_ROSTER_PlayerID
FOREIGN KEY (PlayerID)
REFERENCES PLAYERS(PlayerID)
ON DELETE NO ACTION
ON UPDATE CASCADE,

CONSTRAINT	FK_ROSTER_TeamID
FOREIGN KEY (TeamID)
REFERENCES TEAMS(TeamID)
ON DELETE CASCADE
ON UPDATE CASCADE
)


