USE Futbol 

INSERT INTO ROSTER(PlayerID, TeamID)
VALUES ('7','1902')

INSERT INTO ROSTER(PlayerID, TeamID)
VALUES ('9','1897')

INSERT INTO ROSTER(PlayerID, TeamID)
VALUES ('20','1900')

INSERT INTO ROSTER(PlayerID, TeamID)
VALUES ('17','1905')

INSERT INTO ROSTER(PlayerID, TeamID)
VALUES ('1', '1902')

INSERT INTO ROSTER(PlayerID, TeamID)
VALUES ('12', '1925')

INSERT INTO ROSTER(PlayerID, TeamID)
VALUES ('19', '1900')



